#!/usr/bin/env python3
"""Compile booking programs.

    python3 tools/booking/build.py

Reads every booking/programs/<id>.json and:
  1. writes booking-lib/programs.js, which the Cloudflare functions import (server-side
     prices, capacity and rules — the browser never decides what is charged);
  2. refreshes the program data inside book/<id>/index.html (between the PROGRAM-DATA markers)
     and the program list inside book/admin/index.html.

Edit a JSON file (prices, capacity, photos, deposit…), run this, commit, push.
Shared single-gender rooms use "same_gender": true, "units" (rooms still in play) and
"occupied" (beds taken outside this system, e.g. [{"gender": "Female", "beds": 1}]).
Rooms that sleep one use "capacity".
To add a new week: copy a JSON file, change the id/dates/rooms, copy book/<id>/ to the new id,
run this.
"""
import glob, json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
REQUIRED = ['id', 'title', 'dates', 'venue', 'currency', 'program_spaces', 'deposit', 'rooms', 'genders', 'terms_url']


def load():
    programs = {}
    for f in sorted(glob.glob(os.path.join(ROOT, 'booking', 'programs', '*.json'))):
        p = json.load(open(f, encoding='utf-8'))
        missing = [k for k in REQUIRED if k not in p]
        if missing:
            raise SystemExit(f'{os.path.basename(f)}: missing {missing}')
        ids = [r['id'] for r in p['rooms']]
        if len(ids) != len(set(ids)):
            raise SystemExit(f"{p['id']}: duplicate room ids")
        genders = {g.lower() for g in p['genders']}
        for r in p['rooms']:
            for k in ('id', 'name', 'price', 'unit', 'sleeps', 'photos'):
                if k not in r:
                    raise SystemExit(f"{p['id']}/{r.get('id')}: missing {k}")
            if r.get('same_gender'):
                # shared, single-gender rooms: physical rooms + beds already taken
                if not isinstance(r.get('units'), int) or r['units'] < 0:
                    raise SystemExit(f"{p['id']}/{r['id']}: same_gender rooms need units (number of rooms)")
                for o in r.get('occupied', []):
                    if o.get('gender') is not None and o['gender'].lower() not in genders:
                        raise SystemExit(f"{p['id']}/{r['id']}: occupied gender must be one of {sorted(genders)} or null")
                    if not 0 < o.get('beds', 0) <= r['sleeps']:
                        raise SystemExit(f"{p['id']}/{r['id']}: occupied beds must be 1..{r['sleeps']}")
                if len(r.get('occupied', [])) > r['units']:
                    raise SystemExit(f"{p['id']}/{r['id']}: more occupied rooms than units")
            elif not isinstance(r.get('capacity'), int):
                raise SystemExit(f"{p['id']}/{r['id']}: missing capacity")
            if not isinstance(r['price'], int) or r['price'] < 0:
                raise SystemExit(f"{p['id']}/{r['id']}: price must be whole euros")
        programs[p['id']] = p
    return programs


def inject(path, start, end, block):
    if not os.path.exists(path):
        return False
    s = open(path, encoding='utf-8').read()
    pat = re.escape(start) + r'.*?' + re.escape(end)
    if not re.search(pat, s, re.S):
        raise SystemExit(f'{path}: markers not found')
    n = re.sub(pat, lambda m: start + block + end, s, count=1, flags=re.S)
    if n != s:
        open(path, 'w', encoding='utf-8').write(n)
    return True


def main():
    programs = load()
    js = ('// GENERATED by tools/booking/build.py from booking/programs/*.json. Do not edit by hand.\n'
          'export default ' + json.dumps(programs, ensure_ascii=False, indent=1) + ';\n')
    open(os.path.join(ROOT, 'booking-lib', 'programs.js'), 'w', encoding='utf-8').write(js)
    print(f'booking-lib/programs.js: {len(programs)} program(s)')
    for pid, p in programs.items():
        data = json.dumps(p, ensure_ascii=False, separators=(',', ':')).replace('</', '<\\/')
        ok = inject(os.path.join(ROOT, 'book', pid, 'index.html'),
                    '<script type="application/json" id="programData">', '</script><!-- /PROGRAM-DATA -->', data)
        print(f"book/{pid}/index.html: {'updated' if ok else 'no page yet'}")
    listing = json.dumps([{'id': p['id'], 'title': p['title'], 'edition': p.get('edition', ''), 'dates': p['dates']}
                          for p in programs.values()], ensure_ascii=False, separators=(',', ':'))
    if inject(os.path.join(ROOT, 'book', 'admin', 'index.html'),
              '<script type="application/json" id="programList">', '</script><!-- /PROGRAM-LIST -->', listing):
        print('book/admin/index.html: updated')


if __name__ == '__main__':
    main()
