// GENERATED by tools/booking/build.py from booking/programs/*.json. Do not edit by hand.
export default {
 "breathcamp-oct-2026": {
  "id": "breathcamp-oct-2026",
  "title": "BreathCamp",
  "edition": "BreathCamp 5",
  "heading": "Choose your room and complete your booking",
  "dates": {
   "start": "2026-10-25",
   "end": "2026-10-31",
   "nights": 6,
   "label": "Sunday 25 – Saturday 31 October 2026",
   "short": "25–31 Oct 2026",
   "medium": "25–31 October 2026"
  },
  "venue": {
   "name": "ASHA Retreat Centre",
   "address": "58034 Castell'Azzara, Province of Grosseto, Italy",
   "region": "Tuscany",
   "country": "IT"
  },
  "currency": "EUR",
  "price_note": "Prices are per person for 6 nights' stay and all meals at ASHA. Your programme fee is paid separately.",
  "program_spaces": 17,
  "max_guests_per_booking": 6,
  "booking_closes": "2026-10-24",
  "deposit": {
   "percent": 20,
   "balance_note": "The remaining balance is paid before you arrive at ASHA."
  },
  "genders": [
   "Female",
   "Male",
   "Non-binary/non-conforming",
   "Transgender"
  ],
  "terms_url": "https://alchemyofbreath.com/terms-and-conditions/breathcamp/",
  "contact": {
   "name": "Maria",
   "email": "generalmanager@asha.global",
   "whatsapp": "+393534527348"
  },
  "hero_image": "asha-campus.jpg",
  "source": {
   "system": "RetreatGuru",
   "program": "breathcamp-oct-25-oct-31-2026-accomodation-only",
   "snapshot": "2026-10-03",
   "note": "Capacity below is the number of places RetreatGuru still offered on the snapshot date."
  },
  "rooms": [
   {
    "id": "twin-ensuite",
    "rg_id": 5,
    "name": "Twin Room Ensuite",
    "category": "shared",
    "bath": "Ensuite",
    "price": 1407,
    "unit": "person",
    "sleeps": 2,
    "capacity": 10,
    "shared_with": "same gender",
    "summary": "Two single beds and a private bathroom shared by just the two of you.",
    "description": "With two single beds to a room, these rooms have a private bathroom that only the two people in the room share, with their own gender. This accommodation is rustic, unique, and cozy. Pricing is per person.",
    "photos": [
     "twin-ensuite-1.jpg",
     "twin-ensuite-2.jpg",
     "twin-ensuite-3.jpg",
     "twin-ensuite-4.jpg",
     "twin-ensuite-5.jpg"
    ],
    "plan": "twin-ensuite-plan.jpg"
   },
   {
    "id": "twin-shared-bath",
    "rg_id": 15,
    "name": "Twin Room, Shared Bathroom",
    "category": "shared",
    "bath": "Shared bathroom",
    "price": 1171,
    "unit": "person",
    "sleeps": 2,
    "capacity": 3,
    "shared_with": "same gender",
    "summary": "Two single beds in a newly renovated three-bedroom cottage with its own living room and kitchen.",
    "description": "Two single beds to a room, shared with the same gender, in a private cottage. The bathroom is shared between four people who may be of mixed gender. This beautiful three-bedroom cottage has its own living room and kitchen, and is newly renovated. Pricing is per person.",
    "photos": [
     "twin-shared-bath-1.jpg",
     "twin-shared-bath-2.jpg",
     "twin-shared-bath-3.jpg",
     "twin-shared-bath-4.jpg"
    ],
    "plan": "twin-shared-bath-plan.jpg"
   },
   {
    "id": "triple-ensuite",
    "rg_id": 19,
    "name": "Shared Room for Three, Ensuite",
    "category": "shared",
    "bath": "Ensuite",
    "price": 1107,
    "unit": "person",
    "sleeps": 3,
    "capacity": 5,
    "shared_with": "same gender",
    "summary": "Three single beds with the room's own bathroom, in a cottage or the Main House.",
    "description": "Each room with three single beds has its own private bathroom. The beds are typically a metre apart, and the room is shared with the same gender. These rooms are in either a private cottage or the Main House. Pricing is per person.",
    "photos": [
     "triple-ensuite-1.jpg",
     "triple-ensuite-2.jpg"
    ],
    "plan": "triple-ensuite-plan.jpg"
   },
   {
    "id": "glamping-single",
    "rg_id": 37,
    "name": "Single Glamping, ASHA Bell Tent",
    "category": "glamping",
    "bath": "Shared facilities",
    "price": 1161,
    "unit": "person",
    "sleeps": 1,
    "capacity": 6,
    "summary": "Your own bell tent with a single mattress and a sitting area, close to nature.",
    "description": "Guests love our bell tents. Single tents are furnished with a single mattress and a sitting area. They are lovely, and so very close to nature. Toilets and showers are close to your tent. Please note: autumn weather in Tuscany can be variable.",
    "photos": [
     "glamping-single-1.jpg",
     "glamping-single-2.jpg",
     "glamping-single-3.jpg"
    ]
   },
   {
    "id": "glamping-twin",
    "rg_id": 44,
    "name": "Twin Glamping, ASHA Bell Tent",
    "category": "glamping",
    "bath": "Shared facilities",
    "price": 1037,
    "unit": "person",
    "sleeps": 2,
    "capacity": 4,
    "shared_with": "one other guest",
    "summary": "A bell tent with two mattresses, shared by two people.",
    "description": "Guests love our bell tents. Twin tents are furnished with two mattresses and shared by two people. They are lovely, and so very close to nature. Toilets and showers are close to your tent. Please note: autumn weather in Tuscany can be variable. Pricing is per person.",
    "photos": [
     "glamping-twin-1.jpg",
     "glamping-twin-2.jpg",
     "glamping-twin-3.jpg"
    ]
   },
   {
    "id": "camper",
    "rg_id": 23,
    "name": "Come in a Camper",
    "category": "camping",
    "bath": "Shared facilities",
    "price": 807,
    "unit": "person",
    "sleeps": 1,
    "capacity": 1,
    "summary": "Bring your camper and enjoy full use of ASHA's facilities.",
    "description": "Campers are welcome at ASHA. Space is limited, so we suggest booking as soon as you can: this is one of our most popular options. You're welcome to use all of our facilities. Would you like to bring a guest? Message us on WhatsApp.",
    "photos": [
     "camper-1.jpg"
    ]
   },
   {
    "id": "own-tent",
    "rg_id": 25,
    "name": "Bring Your Own Tent",
    "category": "camping",
    "bath": "Shared facilities",
    "price": 761,
    "unit": "person",
    "sleeps": 1,
    "capacity": 1,
    "summary": "Pitch your own tent in our secluded woods.",
    "description": "Pitch your own tent in our secluded woods, with full use of our facilities. Be sure to bring your own tent, bedding, and anything else you may need. Please note: autumn weather in Tuscany can be variable.",
    "photos": [
     "own-tent-1.jpg",
     "own-tent-2.jpg"
    ]
   },
   {
    "id": "single-ensuite",
    "rg_id": 16,
    "name": "Private Single Room Ensuite",
    "category": "private",
    "bath": "Ensuite",
    "price": 1857,
    "unit": "person",
    "sleeps": 1,
    "capacity": 0,
    "summary": "A private room with its own bathroom in the Main House.",
    "description": "Enjoy a private room with its own bathroom in the Main House. It's perfect for one person, with its own single bed and a desk. In your own private oasis, rest, process, and be in your own space.",
    "photos": [
     "single-ensuite-1.jpg",
     "single-ensuite-2.jpg",
     "single-ensuite-3.jpg"
    ],
    "plan": "single-ensuite-plan.jpg"
   },
   {
    "id": "cottage-one",
    "rg_id": 491,
    "name": "Private Cottage for One",
    "category": "private",
    "bath": "Private bathroom",
    "price": 2612,
    "unit": "person",
    "sleeps": 1,
    "capacity": 0,
    "summary": "A cozy private cottage, all to yourself.",
    "description": "Cozy private cottage accommodation for one person, offering comfort, privacy, and a peaceful stay.",
    "photos": [
     "cottage-one-1.jpg"
    ]
   },
   {
    "id": "cottage-two",
    "rg_id": 18,
    "name": "Private Cottage for Two",
    "category": "private",
    "bath": "Private bathroom",
    "price": 5224,
    "unit": "cottage",
    "sleeps": 2,
    "capacity": 0,
    "summary": "A two-room cottage facing an open field. The price covers both guests.",
    "description": "A two-room cottage in a private house facing an open field, with a cozy living room, kitchen, private bathroom, and a double pull-out sofa bed. Ideal for couples, families, or anyone who wants space. The price is for the whole cottage and covers two guests.",
    "photos": [
     "cottage-two-1.jpg"
    ]
   }
  ]
 }
};
